//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace QUANLYNHANSU
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QuanlynhansuEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QuanlynhansuEntities object using the connection string found in the 'QuanlynhansuEntities' section of the application configuration file.
        /// </summary>
        public QuanlynhansuEntities() : base("name=QuanlynhansuEntities", "QuanlynhansuEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QuanlynhansuEntities object.
        /// </summary>
        public QuanlynhansuEntities(string connectionString) : base(connectionString, "QuanlynhansuEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QuanlynhansuEntities object.
        /// </summary>
        public QuanlynhansuEntities(EntityConnection connection) : base(connection, "QuanlynhansuEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NHANSU> NHANSUs
        {
            get
            {
                if ((_NHANSUs == null))
                {
                    _NHANSUs = base.CreateObjectSet<NHANSU>("NHANSUs");
                }
                return _NHANSUs;
            }
        }
        private ObjectSet<NHANSU> _NHANSUs;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NHANSUs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNHANSUs(NHANSU nHANSU)
        {
            base.AddObject("NHANSUs", nHANSU);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanlynhansuModel", Name="NHANSU")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NHANSU : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NHANSU object.
        /// </summary>
        /// <param name="ten">Initial value of the ten property.</param>
        /// <param name="maso">Initial value of the maso property.</param>
        /// <param name="quequan">Initial value of the quequan property.</param>
        /// <param name="ngaysinh">Initial value of the ngaysinh property.</param>
        /// <param name="gioitinh">Initial value of the gioitinh property.</param>
        /// <param name="sdt">Initial value of the sdt property.</param>
        public static NHANSU CreateNHANSU(global::System.String ten, global::System.String maso, global::System.String quequan, global::System.DateTime ngaysinh, global::System.String gioitinh, global::System.String sdt)
        {
            NHANSU nHANSU = new NHANSU();
            nHANSU.ten = ten;
            nHANSU.maso = maso;
            nHANSU.quequan = quequan;
            nHANSU.ngaysinh = ngaysinh;
            nHANSU.gioitinh = gioitinh;
            nHANSU.sdt = sdt;
            return nHANSU;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ten
        {
            get
            {
                return _ten;
            }
            set
            {
                OntenChanging(value);
                ReportPropertyChanging("ten");
                _ten = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ten");
                OntenChanged();
            }
        }
        private global::System.String _ten;
        partial void OntenChanging(global::System.String value);
        partial void OntenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String maso
        {
            get
            {
                return _maso;
            }
            set
            {
                if (_maso != value)
                {
                    OnmasoChanging(value);
                    ReportPropertyChanging("maso");
                    _maso = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("maso");
                    OnmasoChanged();
                }
            }
        }
        private global::System.String _maso;
        partial void OnmasoChanging(global::System.String value);
        partial void OnmasoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String quequan
        {
            get
            {
                return _quequan;
            }
            set
            {
                OnquequanChanging(value);
                ReportPropertyChanging("quequan");
                _quequan = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("quequan");
                OnquequanChanged();
            }
        }
        private global::System.String _quequan;
        partial void OnquequanChanging(global::System.String value);
        partial void OnquequanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ngaysinh
        {
            get
            {
                return _ngaysinh;
            }
            set
            {
                OnngaysinhChanging(value);
                ReportPropertyChanging("ngaysinh");
                _ngaysinh = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ngaysinh");
                OnngaysinhChanged();
            }
        }
        private global::System.DateTime _ngaysinh;
        partial void OnngaysinhChanging(global::System.DateTime value);
        partial void OnngaysinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gioitinh
        {
            get
            {
                return _gioitinh;
            }
            set
            {
                OngioitinhChanging(value);
                ReportPropertyChanging("gioitinh");
                _gioitinh = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("gioitinh");
                OngioitinhChanged();
            }
        }
        private global::System.String _gioitinh;
        partial void OngioitinhChanging(global::System.String value);
        partial void OngioitinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sdt
        {
            get
            {
                return _sdt;
            }
            set
            {
                OnsdtChanging(value);
                ReportPropertyChanging("sdt");
                _sdt = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sdt");
                OnsdtChanged();
            }
        }
        private global::System.String _sdt;
        partial void OnsdtChanging(global::System.String value);
        partial void OnsdtChanged();

        #endregion

    
    }

    #endregion

    
}
